# Assignment: Bank Account
# MandatoryDeadline: Tuesday of Week 1Difficulty Level: IntermediateEstimated Time: 2-4 hrs
# We are going to create a Bank Account class. This class will recreate some of the common Account transactions that normally occur for a bank account such as displaying your account number, checking and savings amount, total amount. Of course, there are also methods to invoke such as depositing a check, checking your balance, withdrawing money
#
# bank_account.rb

# BankAccount should have a method that returns a user's account number, account number should be generated by a private method, account number should be random
#
# BankAccount should have a method that returns the user's checking account balance
#
# BankAccount should have a method that returns the user's saving account balance
#
# BankAccount should allow a user to deposit money into either their checking or saving account
#
# BankAccount should allow a user to withdraw money from one of their accounts, return an error if there are insufficient funds
#
# BankAccount should allow the user to view the total amount of money they have at the bank
#
# BankAccount should track how many accounts the bank currently has
#
# BankAccount should have a private attribute called interest rate that is only displayed when the user calls the method account_information
#
# BankAccount should have a method called account_information that displays the users account number, total money, checking account balance, saving account balance and interest rate
#
# A user should not be able to set any attributes from the BankAccount class

class BankAccount

end
